export const FETCH_OCCASIONS_PAGE = "FETCH_OCCASIONS_PAGE";
export const FETCH_OCCASIONS_PAGE_START = "FETCH_OCCASIONS_PAGE_START";
export const FETCH_OCCASIONS_PAGE_SUCCESS = "FETCH_OCCASIONS_PAGE_SUCCESS";
export const FETCH_OCCASIONS_PAGE_FAIL = "FETCH_OCCASIONS_PAGE_FAIL";

export const UPDATE_OCCASION = "UPDATE_OCCASION";
export const UPDATE_OCCASION_START = "UPDATE_OCCASION_START";
export const UPDATE_OCCASION_SUCCESS = "UPDATE_OCCASION_SUCCESS";
export const UPDATE_OCCASION_FAIL = "UPDATE_OCCASION_FAIL";

export const FETCH_EVENTS = "FETCH_EVENTS";
export const FETCH_EVENTS_START = "FETCH_EVENTS_START";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_FAIL = "FETCH_EVENTS_FAIL";

export const AUTH_CHECK_INITIAL_STATE = "AUTH_CHECK_INITIAL_STATE";
export const AUTH_USER = "AUTH_USER";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
