export const SELECT_DATE = 'SELECT_DATE';
export const FETCH_EVENTS_START = 'FETCH_EVENTS_START';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_FAIL = 'FETCH_EVENTS_FAIL';
export const SELECT_LANGUAGE = 'SELECT_LANGUAGE';